connectedin/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('perfis.urls')),
    url(r'^', include('usuarios.urls'))
]

perfis/urls.py
from django.conf.urls import url
from perfis import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^perfis/(?P<perfil_id>\d+)$', views.exibir, name='exibir'),
    url(r'^perfis/(?P<perfil_id>\d+)/convidar$', views.convidar,
                                                    name='convidar'),
    url(r'^convite/(?P<id_convite>\d+)/aceitar$', views.aceitar,
                                                    name='aceitar'),

]

usuarios/urls.py
from django.conf.urls import url
from usuarios import views
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^registrar$', views.RegistrarUsuarioView.as_view(),
        name="registrar"),
    url(r'^login/$', login, {'template_name':'login.html'}, name='login'),
    url(r'^logout/$', logout_then_login, { 'login_url': '/login/' },
        name='logout')
]

perfis/models.py
from django.db import models
from django.contrib.auth.models import User

class Perfil(models.Model):
    nome = models.CharField(max_length=40, null=False)
    email = models.EmailField(max_length=100, null=False)
    telefone = models.CharField(max_length=15, null=False)
    nome_empresa = models.CharField(max_length=50, null=False)
    contatos = models.ManyToManyField('self')
    usuario = models.OneToOneField(User, related_name='perfil')

    def convidar(self, perfil_convidado):
        Convite(solicitante=self, convidado=perfil_convidado).save()

class Convite(models.Model):
    solicitante = models.ForeignKey(Perfil, related_name='convites_feitos')
    convidado = models.ForeignKey(Perfil, related_name='convites_recebidos')

    def aceitar(self):
        self.convidado.contatos.add(self.solicitante)
        self.solicitante.contatos.add(self.convidado)
        self.delete()

usuarios/models.py
from django.db import models

# Create your models here.

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrarUsuarioForm(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.CharField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)

    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados informados')
            valid = False

        user_exists = User.objects.filter(username=self.data['nome']).exists()
        if user_exists:
            self.adiciona_erro('Usuario ja existente')
            valid = False

        return valid

    def adiciona_erro(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS,
            forms.utils.ErrorList())
        errors.append(message)

perfis/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from perfis.models import Perfil, Convite
from django.contrib.auth.decorators import login_required, permission_required

@login_required
def index(request):
    print(request.user.username)
    print(request.user.email)
    print(request.user.has_perm('perfis.add_convite'))

    return render(request, 'index.html', {'perfis': Perfil.objects.all(), 'perfil_logado': get_perfil_logado(request) })

@login_required
def exibir(request, perfil_id):
    perfil = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_perfil_logado(request)
    eh_contato = perfil in perfil_logado.contatos.all()
    return render(request, 'perfil.html', {"perfil": perfil, 'eh_contato': eh_contato})

#@permission_required('perfis.add_convite', raise_exception=True)
@login_required
def convidar(request, perfil_id):
    perfil_a_convidar = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_perfil_logado(request)
    perfil_logado.convidar(perfil_a_convidar)
    return redirect('index')

@login_required
def aceitar(request, id_convite):
    convite = Convite.objects.get(id=id_convite)
    convite.aceitar()
    return redirect('index')

@login_required
def get_perfil_logado(request):
    return request.user.perfil

usuarios/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.contrib.auth.models import User
from usuarios.forms import RegistrarUsuarioForm
from perfis.models import Perfil

class RegistrarUsuarioView(View):
    template_name = 'registrar.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        form = RegistrarUsuarioForm(request.POST)
        if form.is_valid():
            dados_form = form.data
            usuario = User.objects.create_user(dados_form['nome'], dados_form['email'], dados_form['senha'])

            perfil = Perfil(nome=dados_form['nome'],
                            email=dados_form['email'],
                            telefone=dados_form['telefone'],
                            nome_empresa=dados_form['nome_empresa'],
                            usuario=usuario)

            perfil.save()
            return redirect('index')

        return render(request, self.template_name, {'form': form})

perfis/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Document</title>
    <link rel="stylesheet" href="{% static "styles/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "styles/main.css" %}">
  </head>
  <body>
    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li><a href="{% url 'index' %}">{{ request.user.username }}</a></li>
          <li><a href="/logout/#">Logout</a></li>
        </ul>
        <h3 class="text-muted">ConnectedIn</h3>
      </div>
      <div class="row content">
        {% block body %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

perfis/templates/index.html
{% extends "base.html" %}
{% block body %}
<div class="col-lg-12">
  <div class="panel panel-default">
      <div class="panel-heading">
        <strong>Todos os perfis</strong>
      </div>
      {% if perfis %}
        <ul>
          {% for perfil in perfis %}
            <li>
              <a href="{% url 'exibir' perfil.id %}">
                {{perfil.nome}} / {{perfil.email}}
              </a>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p>Nenhum perfil encontrado!</p>
      {% endif %}
  </div>

  <div class="panel panel-default">
    {% with total_convites=perfil_logado.convites_recebidos.count %}
      {% if total_convites %}
      <div class="panel-heading">
        <strong>Você tem {{ total_convites }}
          convite{{ total_convites | pluralize }} aguardando aprovação</strong>
      </div>
      <ul class="list-group">
        {% for convite in perfil_logado.convites_recebidos.all %}
          <li class="list-group-item">
            {{ convite.solicitante.nome }}
            <a href="{% url 'aceitar' convite.id %}" class="pull-right">Aceitar</a>
          </li>
        {% endfor %}
      </ul>
      {% else %}
      <div class="panel-body">
        <p>Nenhum convite recebido :(</p>
      </div>
      {% endif %}
    {% endwith %}
  </div>

  <div class="panel panel-default">
    {% with total_contatos=perfil_logado.contatos.count %}
      {% if total_contatos %}
      <div class="panel-heading">
        <strong>Você tem {{ total_contatos }}
          contato{{ total_contatos | pluralize }}</strong>
      </div>
      <ul class="list-group">
        {% for contato in perfil_logado.contatos.all %}
          <li class="list-group-item">
            <a href="{% url 'exibir' contato.id %}">{{ contato.nome }}</a>
          </li>
        {% endfor %}
      </ul>
      {% else %}
      <div class="panel-body">
        <p>Você não possuí contatos no momento :(</p>
      </div>
      {% endif %}
    {% endwith %}
  </div>
</div>
{% endblock %}

perfis/templates/perfil.html
{% extends "base.html" %}
{% block body %}
<div class="row">
  <div class="col-lg-12">
    <h2 style="margin-top: 0">{{ perfil.nome }}</h2>

    <address class="">
      <strong>{{ perfil.nome_empresa }}</strong>
      <br>
      <abbr title="Telefone">Tel:</abbr> {{ perfil.telefone }}
      <br>
      <a href="mailto:{{ perfil.email }}">{{ perfil.email }}</a>
    </address>
    {% if eh_contato %}
    <div class="well well-sm">
      Vocês estão conectados :)
    </div>
    {% else %}
      <a href="{% url 'convidar' perfil.id %}">Convidar</a>
    {% endif %}
  </div>
</div>
{% endblock %}

usuarios/templates/base_usuario.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>ConnectedIn</title>
    <link rel="stylesheet" href="{% static "styles/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "styles/singin.css" %}">
  </head>
  <body>
    <div class="container">
      {% block body %}
      {% endblock %}
    </div>
  </body>
</html>

usuarios/templates/login.html
{% extends "base_usuario.html" %}

{% block body %}

    <form class="form-signin" role="form" action="{% url 'login' %}" method="post">
        {% csrf_token %}

        <h2 class="form-signin-heading">Login</h2>

        <input type="text" id="id_username" name="username" class="form-control" placeholder="Nome" required autofocus>

        <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>

        <input type="hidden" name="next" value="{{ next }}" />

        {% if form.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Por favor, verifique o Email e/ou Senha informados
          </div>
        {% endif %}

        <a href="{% url 'registrar' %}">registre-se</a>
    </form>

{% endblock %}

usuarios/templates/registrar.html
<!-- connectedin/usuarios/templates/registrar.html -->

{% extends "base_usuario.html" %}

{% block body %}

  <form class="form-signin" action="{% url 'registrar' %}" method="post">
    {% csrf_token %}

    <h2 class="form-signin-heading">Crie seu usuário</h2>

    <input type="email" id="id_email" name="email" class="form-control" placeholder="Email *" required autofocus>

    <input type="text" id="id_nome" name="nome" class="form-control" placeholder="Nome *" required >

    <input type="password" id="id_senha" name="senha" class="form-control"  placeholder="Senha *" required>

    <hr />

    <input type="text" id="id_telefone" name="telefone" class="form-control" placeholder="Telefone">

    <input type="text" id="id_nome_empresa" name="nome_empresa" class="form-control" placeholder="Empresa">

    <hr />

    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>

<!-- if novo aqui -->

    <hr/>

     {% if form.errors %}
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{form.non_field_errors}}
      </div>
    {% endif %}

<!-- fim if novo -->


  </form>

{% endblock %}